"$schema" = 'https://starship.rs/config-schema.json'

format = """[ ](bg:#585858)\
$os\
$username\
[](bg:#444444 fg:#585858)\
$hostname\
[](bg:#BFFF7F fg:#444444)\
$directory\
[](fg:#BFFF7F) \
$fill\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$python
[ % ](bg:#303030)\
[](fg:#303030) 
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#585858"
style_root = "bg:#585858"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#585858"
disabled = true # Disabled by default

[fill]
symbol = " "

[hostname]
ssh_only = false
style = "bg:#444444"
format = '[$ssh_symbol]($style)[ $hostname ]($style)'

[directory]
style = "fg:#303030 bg:#BFFF7F"
read_only = ''
read_only_style="fg:#AF0000 bg:#BFFF7F"
format = '[ $path ]($style)[$read_only]($read_only_style)'
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#444444"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#303030 bg:#B2B2FF"
format = '[](fg:#B2B2FF)[ $symbol $branch ]($style)'

[git_status]
style = "fg:#FF0000 bg:#B2B2FF"
format = '[$all_status$ahead_behind ]($style)[](bg:#B2B2FF fg:#B2B2FF fg:#303030)'

[golang]
symbol = " "
style = "bg:#444444"
format = '[](fg:#444444)[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#444444"
format = '[](fg:#444444)[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#444444"
format = '[](fg:#444444)[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#444444"
format = '[](fg:#444444)[ $symbol ($version) ]($style)'

[rust]
symbol = " "
style = "bg:#444444"
format = '[](fg:#444444)[ $symbol ($version) ]($style)'
[python]
symbol = " "
style = "bg:#444444"
format = '[](fg:#444444)[ $symbol ($version) ]($style)'
